### ISSUE TITLE
db_getchatlist should return unique values

### ISSUE THREAD

**Issue by marcocucinato** [auino/php-telegram-bot-library#7]
If used with the send.php code, the db_getchatlist() function should return only unique values, else the broadcast messages will be duplicated.
line 13 of /lib/log.php should be changed from

`$q = "SELECT chat FROM Logs WHERE bot='$botname';";`

to 

`$q = "SELECT DISTINCT chat FROM Logs WHERE bot='$botname';";`

**Comment by auino** [comment]
Thank you: it's true!
Nevertheless, due to early tests, if the program is running on a low-performance host (in my case, at time of writing the library, a first version RPI), the `DISTINCT` keyword would degrade performance.
Hence, I've added a new `$ISLOWPERFORMANCEHOST` parameter in `config.php` (default to `false`) to enable/disable the new keyword.
Before closing the issue, please let me know if you have suggestions about this aspect.

**Comment by marcocucinato** [comment]
Hello,

maybe creating an index on 'chat' field could speed-up the query.

I created an index :
`ALTER TABLE 'telegram'.'Logs' DROP INDEX 'chat', ADD INDEX 'chat' ('chat') USING BTREE;`
and I tried to execute the query
`SELECT DISTINCT chat FROM 'Logs' USE INDEX (chat)`
but I don't see a lot of difference, as I have just 20 records in Logs table.

I souhld try to populate the table with some thousands of records, and do a profiling with the index and without it.

**Comment by marcocucinato** [comment]
I just tried... i found a nice website ([http://filldb.info/](http://filldb.info/)) to create dummy data.
I injected 10,000 rows, still my server is very powerful... Still, I get a 40-45% speed-up.

with `SELECT DISTINCT chat FROM 'Logs'  USE index (chat)` i got 501 rows in 0.0029s

with `SELECT DISTINCT chat FROM 'Logs'  IGNORE index (chat)` I got 501 rows in 0.0043s

**Comment by auino** [comment]
Thank you very much, I've opted for such solution (and just updated the code).
